#!/bin/sh
#
if [ "$#" -ne 2 ]
then
    echo "You have to assign an input file and a project ID!!"
    echo "<< Job not submitted !! >>"
    exit
fi

JOB=$1
USER=`whoami`
HERE=`pwd`

PID=$2

if [ -f ${JOB}.ab ]
then
    /bin/rm ${JOB}.ab
fi

QUE=1cpu
NCPUS=1

echo "Input the number of CPU-core to run your job: "
echo "1cpu, 8cpu, 14cpu, 20cpu? [$QUE] "
read QUE

if [ -z "$QUE" ]
  then
  QUEUE=ct112
  NCPUS=1
  NNODE=1
  NPROC=1
  NTOKEN=5
fi

if [ "$QUE" = 1cpu ]
then
  QUEUE=ct112
  NCPUS=1
  NNODE=1
  NPROC=1
  NTOKEN=5
fi

if [ "$QUE" = 8cpu ]
then
  QUEUE=ct112
  NCPUS=8
  NNODE=1
  NPROC=8
  NTOKEN=12
fi

if [ "$QUE" = 14cpu ]
then
  QUEUE=ct112
  NCPUS=14
  NNODE=1
  NPROC=14
  NTOKEN=15
fi

if [ "$QUE" = 20cpu ]
then
  QUEUE=ct112
  NCPUS=20
  NNODE=1
  NPROC=20
  NTOKEN=17
fi

cat << END_OF_CAT > $JOB.ab
#!/bin/bash -l
#SBATCH -A $PID
#SBATCH -J $JOB
#SBATCH -p $QUEUE
#SBATCH -N $NNODE
#SBATCH -c 1
#SBATCH --ntasks-per-node=$NCPUS
#SBATCH -o $JOB.out
#SBATCH -e $JOB.err

### Load ABAQUS
module load apps/abaqus/2024

### Configure environment variables, need to unset SLURM's Global Task ID for ABAQUS's PlatformMPI to work
unset SLURM_GTIDS

### Create ABAQUS environment file for current job, you can set/add your own options (Python syntax)
env_file=abaqus_v6.env

node_list=\$(scontrol show hostname \${SLURM_NODELIST} | sort -u)

mp_host_list="["
for host in \${node_list}; do
    mp_host_list="\${mp_host_list}['\$host', $NCPUS],"
done

mp_host_list=\$(echo \${mp_host_list} | sed -e "s/,\$/]/")

echo "mp_host_list=\${mp_host_list}"  > \${env_file}

echo \"Starting on \`hostname\` at \`date\`\"

echo "# JOBID is: \${SLURM_JOBID}" >>  $HERE/abaqus_v6.env

abaqus job=$JOB cpus=$NPROC mp_mode=mpi interactive

wait

echo \"Your ABAQUS job completed at  \`date\` \"

END_OF_CAT

#
chmod +x $JOB.ab
#
sbatch < $JOB.ab

exit
